swagger: "2.0"
info:
  version: "1.0.0"
  title: "Company API"
paths:
  /employees/:
    get:
      summary: "Get a list of employees"
      description: "Retrieve a list of employees with optional filtering by last name."
      parameters:
        - name: page
          in: query
          description: "Employee list page."
          type: int
        - name: last_name
          in: query
          description: "Filter employees by last name."
          type: string
        - name: department
          in: query
          description: "Filter employees by department id."
          type: int
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Employee"
    post:
      summary: "Create a new employee"
      description: "Create a new employee with the provided data."
      parameters:
        - name: employee
          in: body
          description: "Employee object"
          required: true
          schema:
            $ref: "#/definitions/Employee"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Employee"

  /employees/{id}/:
    get:
      summary: "Retrieve an employee"
      description: "Retrieve the details of a specific employee."
      parameters:
        - name: id
          in: path
          description: "Employee ID"
          type: integer
          required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Employee"
    put:
      summary: "Update an employee"
      description: "Update the details of a specific employee."
      parameters:
        - name: id
          in: path
          description: "Employee ID"
          type: integer
          required: true
        - name: employee
          in: body
          description: "Employee object"
          required: true
          schema:
            $ref: "#/definitions/Employee"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Employee"
    delete:
      summary: "Delete an employee"
      description: "Delete a specific employee."
      parameters:
        - name: id
          in: path
          description: "Employee ID"
          type: integer
          required: true
      responses:
        204:
          description: "No Content"

  /departments/:
    get:
      summary: "Get a list of departments"
      description: "Retrieve a list of departments."
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Department"

definitions:
  Employee:
    type: object
    properties:
      id:
        type: integer
      full_name:
        type: string
      photo:
        type: string
      position:
        type: string
      salary:
        type: number
      age:
        type: integer

  Department:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      director:
        type: string
      num_employees:
        type: integer
      total_salary:
        type: number
